.TH TETRIS "2016" Tetris "Tetris"
.SH NAME
tetris \- simple ncurses tetris game
.SH SYNOPSIS
.B tetris [-hv]
.SH DESCRIPTION
.B tetris
is a simple console based tetris game built using the ncurses library.
.SH OPTIONS
.IP -h
Display a short help message and exit
.IP -v
Display version string and exit
.SH BUGS
If you resize the terminal while the program is running, the screen becomes corrupted
.SH AUTHOR
Alessandro Righi <alerighi4@gmail.com>
.SH COPYRIGHT
You are free to use, modify and redistribuite this program uder the terms of the BSD licence
