.TH TETRIS "6" Tetris "Tetris"
.SH NAME
tetris \- simple ncurses tetris game
.SH SYNOPSIS
.B tetris [-hv]
.SH DESCRIPTION
.B tetris
is a simple console based tetris game built using the ncurses library.
.SH OPTIONS
.IP -h
Display a short help message and exit
.IP -v
Display version string and exit
.SH NEW FEATURES 
.B 1.1.0
.br
High score savaved to file ($HOME/.tetris_score)
.br
Bug fix
.SH BUGS
If you resize the terminal while the program is running, the screen becomes corrupted
.SH AUTHOR
Alessandro Righi <alerighi4@gmail.com>
.SH COPYRIGHT
This software is free software, relased under the terms of the MIT licence